sudo: false
language: java
before_install:
- openssl aes-256-cbc -K $encrypted_b8f97d8bbd75_key -iv $encrypted_b8f97d8bbd75_iv
  -in key.txt.enc -out key.txt -d
- source key.txt
- gcc --version
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
- echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa*
- eval `ssh-agent -s`
- ssh-add ~/.ssh/id_rsa
- export BUILD_ID=`date +%Y%m%d_%H%M%S`
install:
- sh scripts/create.sh
env:
  global:
  - secure: N50IDjBu6YLbJ/9XYvBF1M4fdCKmDVLHm2GLeEM5mOgUXdwvC1RPndGBByq4GT6fUHEB5gN8g5y/dbkbWgO7BISRlM178ualh+AuIHRZglNQFmip3jlTSc6bkqb3rVkx/MdKueDpBg+lmku8y+x661gWlFfxGGGPKopazX4uaaA=
  - secure: iDUgrVU11fQZXsRao9wZ2Kgmid/o+t7p4pXWs2WFnCzs9+nSnvek7sFUHLGk4hackJhDgAZxMnA+1dfrKbnAd5/V58PpF+cJc1P1tJVsPNcFyWwG+MAF0IsC5PTZ0DuU2ah3b7K2X8xYO/6USldpeFim8jeqQDi3CBxK0VLXQl0=
